---
variables:
  KOJI_TAG: "cboxops"
  BUILD_7: "True"
  DIST_7: ".el7.cern"
  ADD_VCS_TAG: "False"

# needed for koji build
include: "https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml"

.rpm_deps:
  before_script:
    - rpmci_add_repo_kojitag_stable
    - rpmci_install_builddeps
    - yum group install -y "Development Tools"
    - rm -rf /usr/local/go
    - wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
